name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start app and run tests
        run: |
          # Start uvicorn in background using the mock DB so tests don't require MongoDB
          export USE_MOCK_DB=1
          python -m uvicorn main:app --host 127.0.0.1 --port 8000 &
          # Wait for the server to become available (max ~15s)
          for i in {1..15}; do
            if curl --silent --fail http://127.0.0.1:8000/history >/dev/null 2>&1; then
              echo 'Server is up';
              break
            fi
            echo 'Waiting for server...'; sleep 1;
          done
          pytest -q
